services:
  caddy:
    image: ghcr.io/lichess4545/litour-caddy:latest
    # ports:
    #   - 8000:80
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
      - litour
    deploy:
      update_config:
        order: start-first

  web:
    image: ghcr.io/lichess4545/litour-web:latest
    env_file: "stack.env"
    environment:
      DATABASE_URL_FILE: /run/secrets/litour_prod_db_url
      SECRET_KEY_FILE: /run/secrets/litour_app_secret_key
      EMAIL_HOST_USER_FILE: /run/secrets/email_host_user
      EMAIL_HOST_PASSWORD_FILE: /run/secrets/email_host_password
    secrets:
      - litour_prod_db_url
      - litour_app_secret_key
      - email_host_user
      - email_host_password
    networks:
      - litour
    deploy:
      update_config:
        order: start-first

  apiworker:
    image: ghcr.io/lichess4545/litour-api-worker:latest
    env_file: "stack.env"
    environment:
      DATABASE_URL_FILE: /run/secrets/litour_prod_db_url
      HELTOUR_ENV: prod
      HELTOUR_APP: api_worker
      SECRET_KEY_FILE: /run/secrets/litour_app_secret_key
      EMAIL_HOST_USER_FILE: /run/secrets/email_host_user
      EMAIL_HOST_PASSWORD_FILE: /run/secrets/email_host_password
    secrets:
      - litour_prod_db_url
      - litour_app_secret_key
      - email_host_user
      - email_host_password
    networks:
      - litour
    deploy:
      update_config:
        order: start-first

  celery:
    image: ghcr.io/lichess4545/litour-celery:latest
    env_file: "stack.env"
    networks:
      - litour
    deploy:
      update_config:
        order: start-first
  
  migrate:
    image: ghcr.io/lichess4545/litour-migrate:latest
    env_file: "stack.env"
    networks:
      - litour
    deploy:
      restart_policy:
        condition: none

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - litour
    deploy:
      update_config:
        order: stop-first

volumes:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  caddy:
    external: true
  litour:
    driver: overlay
    # driver: bridge

secrets:
  litour_prod_db_url:
    external: true
  litour_db_password:
    external: true
  litour_app_secret_key:
    external: true
  email_host_user:
    external: true
  email_host_password:
    external: true
