/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List discoverable events. */
        get: operations["list_events_route_v1_discovery_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event detail (header + composed pairings + tab availability). */
        get: operations["event_detail_route_v1_discovery_events__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{league_tag}/current-round": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Round */
        get: operations["current_round_v1_leagues__league_tag__current_round_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{league_tag}/events/{event_tag}/rounds/{round_number}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Round Matches By Slug */
        get: operations["round_matches_by_slug_v1_leagues__league_tag__events__event_tag__rounds__round_number__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Match Result */
        put: operations["set_match_result_v1_matches__match_id__result_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round_management/cockpit/{pairing_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cockpit Audit */
        get: operations["get_cockpit_audit_v1_round_management_cockpit__pairing_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round_management/cockpit/{pairing_id}/force-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Force Result */
        post: operations["post_force_result_v1_round_management_cockpit__pairing_id__force_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round_management/cockpit/{pairing_id}/mark-forfeit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Mark Forfeit */
        post: operations["post_mark_forfeit_v1_round_management_cockpit__pairing_id__mark_forfeit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round_management/cockpit/{pairing_id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Reschedule */
        post: operations["post_reschedule_v1_round_management_cockpit__pairing_id__reschedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/round_management/events/{event_slug}/cockpit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cockpit */
        get: operations["get_cockpit_v1_round_management_events__event_slug__cockpit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds/{round_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Round Matches By Id */
        get: operations["round_matches_by_id_v1_rounds__round_id__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CockpitAttentionDTO */
        AttentionDTO: {
            /**
             * Level
             * @enum {string}
             */
            level: "none" | "watch" | "act";
            /** Reasons */
            reasons: ("no_schedule_near_deadline" | "scheduled_but_not_started" | "past_deadline_no_result")[];
        };
        /** CockpitAuditEntryDTO */
        CockpitAuditEntryDTO: {
            /** Actor Username */
            actor_username: string;
            /** After Summary */
            after_summary: string;
            /** Before Summary */
            before_summary: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /**
             * Intervention Type
             * @enum {string}
             */
            intervention_type: "force_result" | "mark_forfeit" | "reschedule";
            /** Pairing Id */
            pairing_id: number;
            /** Reason */
            reason: string;
        };
        /** CockpitDTO */
        CockpitDTO: {
            /** Event Name */
            event_name: string;
            /** Event Tag */
            event_tag: string;
            /** Is Completed */
            is_completed: boolean;
            /** Is Team */
            is_team: boolean;
            /** Last Event Id */
            last_event_id: number;
            /** League Tag */
            league_tag: string;
            /** Matches */
            matches: components["schemas"]["CockpitMatchDTO"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "pre_round" | "history" | "empty";
            /** Needs You Count */
            needs_you_count: number;
            /** Presence Events */
            presence_events: {
                [key: string]: components["schemas"]["MatchPresenceDTO"];
            };
            /** Round Deadline */
            round_deadline: string | null;
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
            /** Rounds */
            rounds: components["schemas"]["EventRoundDTO"][];
            settings: components["schemas"]["EventSettingsDTO"];
            /** Team Matches */
            team_matches: components["schemas"]["TeamMatchDTO"][];
            viewer: components["schemas"]["CockpitViewerDTO"];
        };
        /** CockpitMatchDTO */
        CockpitMatchDTO: {
            attention: components["schemas"]["AttentionDTO"];
            /** Black Fide Name */
            black_fide_name: string | null;
            /** Black Gender */
            black_gender: string | null;
            /** Black Is Captain */
            black_is_captain: boolean;
            /** Black Rating */
            black_rating: number | null;
            /** Black Username */
            black_username: string | null;
            /** Board Number */
            board_number: number | null;
            /** Game Link */
            game_link: string;
            /** Id */
            id: number;
            /** Result */
            result: string;
            /** Scheduled At */
            scheduled_at: string | null;
            /** Team Match Id */
            team_match_id: number | null;
            /** Version */
            version: number;
            /** White Fide Name */
            white_fide_name: string | null;
            /** White Gender */
            white_gender: string | null;
            /** White Is Captain */
            white_is_captain: boolean;
            /** White Rating */
            white_rating: number | null;
            /** White Username */
            white_username: string | null;
        };
        /**
         * CockpitViewerDTO
         * @description Cockpit-scoped viewer flags (DR per design doc ER3 field tier).
         *
         *     Adds the per-intervention capability flags so the UI can choose which
         *     drawer controls to render without per-pairing roundtrips.
         */
        CockpitViewerDTO: {
            /** Can Edit Pairings */
            can_edit_pairings: boolean;
            /** Can Force Result */
            can_force_result: boolean;
            /** Can Mark Forfeit */
            can_mark_forfeit: boolean;
            /** Can Reschedule */
            can_reschedule: boolean;
            /** Can View Presence Log */
            can_view_presence_log: boolean;
            /** Is Authenticated */
            is_authenticated: boolean;
        };
        /** CurrentRoundDTO */
        CurrentRoundDTO: {
            /** Event Name */
            event_name: string;
            /** Event Tag */
            event_tag: string;
            /** League Tag */
            league_tag: string;
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
        };
        /**
         * EventCardDTO
         * @description The shape rendered into one card on /v2/.
         *
         *     Card hierarchy (DESIGN.md): name -> status pill -> organizer label
         *     -> format / schedule -> slot status. Field order in this class
         *     matches that visual order to make the contract self-documenting.
         */
        EventCardDTO: {
            /**
             * Format Line
             * @description Composed format summary, e.g. "Team Swiss · 8 rounds".
             */
            format_line: string;
            /**
             * Name
             * @description Tournament name (Season.name).
             */
            name: string;
            /**
             * Organizer Label
             * @description Organizer name shown under the tournament title.
             */
            organizer_label: string;
            /**
             * Organizer Tag
             * @description Machine slug for the organizer chip filter. Currently League.tag.
             */
            organizer_tag: string;
            /**
             * Registration Url
             * @description Absolute path that the Register CTA links to (legacy Django form).
             */
            registration_url: string;
            /**
             * Schedule Line
             * @description Composed schedule summary, e.g. "45+45 · Sundays 11am UTC". Empty string when start_date is unset.
             */
            schedule_line: string;
            /**
             * Slot Status
             * @description Free-form status string the card renders next to the pill, e.g. "Round 4 of 8" for active events or "23 / 32 players" for open ones. Empty string for finished events.
             */
            slot_status: string;
            /**
             * Slug
             * @description Globally-unique URL identifier.
             */
            slug: string;
            /**
             * Status Group
             * @description Machine status key. URL filter contract: ?status=active|upcoming|completed.
             * @enum {string}
             */
            status_group: "active" | "upcoming" | "awaiting" | "completed";
            /**
             * Status Label
             * @description Display string for the status pill. Chess-native per DESIGN.md.
             * @enum {string}
             */
            status_label: "Now playing" | "Open" | "Awaiting results" | "Finished";
            /**
             * Visibility
             * @description Carried for the noindex hint on detail pages.
             * @enum {string}
             */
            visibility: "public" | "unlisted" | "draft";
        };
        /**
         * EventCardsPage
         * @description Paginated card list returned by GET /v1/discovery/events.
         *
         *     `total` is the unpaginated count after filters apply, for client-side
         *     pagination UIs that render "Showing N of T".
         */
        EventCardsPage: {
            /** Events */
            events: components["schemas"]["EventCardDTO"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * EventDetailDTO
         * @description Full payload for GET /v1/discovery/events/<slug>.
         *
         *     `tabs_available` lists the machine names of tabs whose payload is
         *     real (not a "Coming soon" placeholder). Frontend reads this to
         *     decide which tabs are interactive vs. disabled.
         */
        EventDetailDTO: {
            header: components["schemas"]["EventHeaderDTO"];
            /**
             * Pairings
             * @description Latest published round's pairings DTO when available, or None when no round has been published yet. Shape: round_management.RoundMatchesDTO.
             */
            pairings?: Record<string, never> | null;
            /**
             * Pairings Error
             * @description True when the pairings DTO failed to build. Distinguishes a rendered empty state ('Pairings will appear once...') from a broken backend ('Couldn't load pairings, retry').
             * @default false
             */
            pairings_error: boolean;
            /**
             * Tabs Available
             * @description Always at least ["pairings"] today. "standings" / "roster" join when their packages graduate from placeholder.
             */
            tabs_available: ("pairings" | "standings" | "roster")[];
        };
        /**
         * EventHeaderDTO
         * @description Header block on /v2/events/<slug>/... (card-shaped, plus richer fields).
         */
        EventHeaderDTO: {
            /**
             * Can Manage
             * @description True when the viewer holds tournament.change_pairing on the league. Drives whether the event page renders a Manage-cockpit link. Always False on signal-pushed payloads (publishers fan out without a viewer).
             * @default false
             */
            can_manage: boolean;
            /** Format Line */
            format_line: string;
            /** Name */
            name: string;
            /** Organizer Label */
            organizer_label: string;
            /** Organizer Tag */
            organizer_tag: string;
            /**
             * Registration Open
             * @description Whether the Register CTA should render as an active button.
             */
            registration_open: boolean;
            /** Registration Url */
            registration_url: string;
            /** Schedule Line */
            schedule_line: string;
            /** Slot Status */
            slot_status: string;
            /** Slug */
            slug: string;
            /**
             * Status Group
             * @enum {string}
             */
            status_group: "active" | "upcoming" | "awaiting" | "completed";
            /**
             * Status Label
             * @enum {string}
             */
            status_label: "Now playing" | "Open" | "Awaiting results" | "Finished";
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "unlisted" | "draft";
        };
        /**
         * EventRoundDTO
         * @description Summary of one round in an Event, used by the round navigator at the
         *     top of round-scoped pages. ``is_published`` mirrors the Django
         *     ``Round.publish_pairings`` flag — pairings are visible to the public
         *     only when this is true; the UI fades unpublished (future) rounds.
         */
        EventRoundDTO: {
            /** Is Completed */
            is_completed: boolean;
            /** Is Published */
            is_published: boolean;
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
        };
        /**
         * EventSettingsDTO
         * @description Display / behaviour preferences resolved for an Event (Season).
         *
         *     Bag of flags rather than scattering each setting onto every DTO that
         *     needs them. Today a few items live on `League` (e.g. `show_fide_names`,
         *     `rating_type`); over time some may move to `Season`. Either way, the
         *     UI consumes them through this single object so callers don't need to
         *     track which model owns which flag.
         */
        EventSettingsDTO: {
            /** Use Fide Information */
            use_fide_information: boolean;
        };
        /** CockpitForceResultRequest */
        ForceResultRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Result
             * @enum {string}
             */
            result: "1-0" | "0-1" | "1/2-1/2";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDTO */
        HealthDTO: {
            /** Ok */
            ok: boolean;
        };
        /** CockpitMarkForfeitRequest */
        MarkForfeitRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Forfeit Side
             * @enum {string}
             */
            forfeit_side: "white" | "black" | "double";
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * MatchDTO
         * @description A single Match. In team Events this is a Player Match (one board of a
         *     Team Match); in lone Events it's a standalone Match.
         *
         *     ``*_username`` is the lichess handle (canonical identity, used for links
         *     to lichess.org/@/<handle>). ``*_fide_name`` is the player's FIDE name
         *     when known. ``*_rating`` is league-resolved (snapshot at game time when
         *     available, falling back to the player's current league rating).
         *     ``*_gender`` is the raw choice value (``male`` / ``female`` /
         *     ``non-binary`` / ``not-represented`` / ``prefer-not-disclose`` / ``""``).
         */
        MatchDTO: {
            /** Black Fide Name */
            black_fide_name: string | null;
            /** Black Gender */
            black_gender: string | null;
            /** Black Is Captain */
            black_is_captain: boolean;
            /** Black Rating */
            black_rating: number | null;
            /** Black Username */
            black_username: string | null;
            /** Board Number */
            board_number: number | null;
            /** Game Link */
            game_link: string;
            /** Id */
            id: number;
            /** Result */
            result: string;
            /** Team Match Id */
            team_match_id: number | null;
            /** White Fide Name */
            white_fide_name: string | null;
            /** White Gender */
            white_gender: string | null;
            /** White Is Captain */
            white_is_captain: boolean;
            /** White Rating */
            white_rating: number | null;
            /** White Username */
            white_username: string | null;
        };
        /**
         * MatchPresenceDTO
         * @description Presence pair — one entry per side of a single match. Keyed on the
         *     round-level map by `match.id` (= the PlayerPairing pk). `null` for a
         *     side means there's no player on that side (bye / unfilled board).
         */
        MatchPresenceDTO: {
            black: components["schemas"]["PlayerPresenceDTO"] | null;
            white: components["schemas"]["PlayerPresenceDTO"] | null;
        };
        /**
         * PlayerPresenceDTO
         * @description Presence info for one player on one match (board pairing).
         *
         *     `was_online` answers "did this player appear online during the round
         *     at all?" — the legacy template's "Online during round" header. The
         *     `events` list is ordered ascending by timestamp.
         */
        PlayerPresenceDTO: {
            /** Events */
            events: components["schemas"]["PresenceEventDTO"][];
            /** Plies Played */
            plies_played: number;
            /** Was Online */
            was_online: boolean;
        };
        /**
         * PresenceEventDTO
         * @description One entry in the staff-visible presence log next to a player.
         *
         *     Mirrors `PlayerPresenceEvent` (heltour/tournament/models.py:4374) — the
         *     same shape the legacy popover renders.
         */
        PresenceEventDTO: {
            /** Event Type */
            event_type: string;
            /** Event Type Display */
            event_type_display: string;
            /** Game Id */
            game_id: string | null;
            /** Timestamp */
            timestamp: string;
        };
        /** CockpitRescheduleRequest */
        RescheduleRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * New Scheduled At
             * Format: date-time
             */
            new_scheduled_at: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** RoundMatchesDTO */
        RoundMatchesDTO: {
            /** Event Name */
            event_name: string;
            /** Event Tag */
            event_tag: string;
            /** Is Completed */
            is_completed: boolean;
            /** Is Team */
            is_team: boolean;
            /** League Tag */
            league_tag: string;
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            /** Presence Events */
            presence_events: {
                [key: string]: components["schemas"]["MatchPresenceDTO"];
            };
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
            /** Rounds */
            rounds: components["schemas"]["EventRoundDTO"][];
            settings: components["schemas"]["EventSettingsDTO"];
            /** Team Matches */
            team_matches: components["schemas"]["TeamMatchDTO"][];
            viewer: components["schemas"]["ViewerDTO"];
        };
        /**
         * SetMatchResultRequest
         * @description Body of the staff-only `PUT /v1/matches/{id}/result` endpoint.
         *
         *     Empty string clears the result. Any other value must be one of
         *     ``RESULT_OPTIONS`` from `heltour/tournament/models.py:2409`; the route
         *     rejects anything else with a 422.
         */
        SetMatchResultRequest: {
            /** Result */
            result: string;
        };
        /**
         * TeamMatchDTO
         * @description A Team Match (Django ``TeamPairing``). Holds the two teams and the
         *     aggregated score; the actual board pairings (Player Matches) are in
         *     ``RoundMatchesDTO.matches`` linked via ``MatchDTO.team_match_id``.
         */
        TeamMatchDTO: {
            /** Black Score */
            black_score: number;
            /** Black Team Name */
            black_team_name: string | null;
            /** Black Team Number */
            black_team_number: number | null;
            /** Id */
            id: number;
            /** Is Bye */
            is_bye: boolean;
            /** Pairing Order */
            pairing_order: number;
            /** White Score */
            white_score: number;
            /** White Team Name */
            white_team_name: string;
            /** White Team Number */
            white_team_number: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ViewerDTO
         * @description Permission flags for the current request's viewer, scoped to one round.
         *
         *     A bag of booleans rather than a single role string so we can grow new
         *     surfaces (move history, tagging, etc.) without renumbering enum values.
         *     Today both flags are gated on the same Django permission
         *     (`tournament.change_pairing` against the league); we keep them
         *     separate so the UI doesn't have to know that.
         */
        ViewerDTO: {
            /** Can Edit Pairings */
            can_edit_pairings: boolean;
            /** Can View Presence Log */
            can_view_presence_log: boolean;
            /** Is Authenticated */
            is_authenticated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
        };
    };
    list_events_route_v1_discovery_events_get: {
        parameters: {
            query?: {
                /** @description Status group filter, repeatable. Default (when omitted) is active + upcoming + awaiting; completed requires an explicit ?status=completed. */
                status?: ("active" | "upcoming" | "awaiting" | "completed")[] | null;
                /** @description Organizer filter by tag (formerly League.tag), repeatable. Omitted = all organizers. Each tag must match [-a-zA-Z0-9_]+ (max 64 chars). */
                organizer?: string[] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCardsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_detail_route_v1_discovery_events__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailDTO"];
                };
            };
            /** @description Not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_round_v1_leagues__league_tag__current_round_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentRoundDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    round_matches_by_slug_v1_leagues__league_tag__events__event_tag__rounds__round_number__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_tag: string;
                event_tag: string;
                round_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundMatchesDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_match_result_v1_matches__match_id__result_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMatchResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDTO"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — viewer lacks change_pairing perm */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Match not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid result code */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_cockpit_audit_v1_round_management_cockpit__pairing_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CockpitAuditEntryDTO"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — viewer lacks change_pairing perm */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Optimistic-concurrency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_force_result_v1_round_management_cockpit__pairing_id__force_result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForceResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CockpitMatchDTO"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — viewer lacks change_pairing perm */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Optimistic-concurrency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_mark_forfeit_v1_round_management_cockpit__pairing_id__mark_forfeit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkForfeitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CockpitMatchDTO"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — viewer lacks change_pairing perm */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Optimistic-concurrency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_reschedule_v1_round_management_cockpit__pairing_id__reschedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CockpitMatchDTO"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — viewer lacks change_pairing perm */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Optimistic-concurrency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_cockpit_v1_round_management_events__event_slug__cockpit_get: {
        parameters: {
            query?: {
                round_id?: number | null;
            };
            header?: never;
            path: {
                event_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CockpitDTO"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — viewer lacks change_pairing perm */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Optimistic-concurrency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    round_matches_by_id_v1_rounds__round_id__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundMatchesDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
