/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{league_tag}/current-round": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Round */
        get: operations["current_round_v1_leagues__league_tag__current_round_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds/{round_id}/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Round Pairings */
        get: operations["round_pairings_v1_rounds__round_id__pairings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CurrentRoundDTO */
        CurrentRoundDTO: {
            /** League Tag */
            league_tag: string;
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
            /** Season Name */
            season_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDTO */
        HealthDTO: {
            /** Ok */
            ok: boolean;
        };
        /** PairingDTO */
        PairingDTO: {
            /** Black Rating */
            black_rating: number | null;
            /** Black Username */
            black_username: string | null;
            /** Board Number */
            board_number: number | null;
            /** Game Link */
            game_link: string;
            /** Id */
            id: number;
            /** Result */
            result: string;
            /** Team Pairing Id */
            team_pairing_id: number | null;
            /** White Rating */
            white_rating: number | null;
            /** White Username */
            white_username: string | null;
        };
        /** RoundPairingsDTO */
        RoundPairingsDTO: {
            /** Is Completed */
            is_completed: boolean;
            /** League Tag */
            league_tag: string;
            /** Pairings */
            pairings: components["schemas"]["PairingDTO"][];
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
            /** Season Name */
            season_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
        };
    };
    current_round_v1_leagues__league_tag__current_round_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentRoundDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    round_pairings_v1_rounds__round_id__pairings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundPairingsDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
