# Generated by Django 4.2.22 on 2025-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0009_alter_playernotificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguesetting",
            name="scheduling",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Do players schedule their games individually, "
                    "or are games started automatically or by an arbiter."
                ),
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="bulk_id",
            field=models.SlugField(default="", null=True),
        ),
    ]
