# Generated by Django 4.2.22 on 2025-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_season_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('fide', 'FIDE')], max_length=32),
        ),
    ]
