# Generated by Django 4.2.22 on 2025-11-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_knockoutbracket_matches_per_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='require_corporate_info',
            field=models.BooleanField(default=False, help_text='If true, require corporate info fields (corporate_email, personal_email, contact_number) during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_fide_id',
            field=models.BooleanField(default=False, help_text='If true, require FIDE ID during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_personal_info',
            field=models.BooleanField(default=False, help_text='If true, require personal info fields (first_name, last_name, gender, date_of_birth, nationality) during registration. Default is false.'),
        ),
    ]
