# Generated by Django 4.2.22 on 2025-11-09 01:25

from django.db import migrations


def set_existing_leagues_to_require_fields(apps, schema_editor):
    """
    Set require_personal_info and require_corporate_info to True for all existing leagues.
    This maintains backward compatibility with the previous hardcoded behavior where
    these fields were always required.

    New leagues created after this migration will have these fields default to False,
    giving tournament organizers the flexibility to choose which fields to require.
    """
    League = apps.get_model('tournament', 'League')

    # Update all existing leagues to require personal and corporate info
    # This preserves the previous behavior where these fields were hardcoded as required
    League.objects.all().update(
        require_personal_info=True,
        require_corporate_info=True,
        # require_fide_id remains False (was optional before, stays optional)
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by setting all leagues back to the new defaults (False).
    """
    League = apps.get_model('tournament', 'League')

    League.objects.all().update(
        require_personal_info=False,
        require_corporate_info=False,
        require_fide_id=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0036_league_require_corporate_info_league_require_fide_id_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_leagues_to_require_fields, reverse_migration),
    ]
