# Generated by Django 4.2.22 on 2026-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0053_playerpairing_plies_played_playerpresenceevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Globally-unique URL identifier for the discovery domain (/v2/events/<slug>/...). Auto-populated on first save from league.tag + tag + id; immutable once assigned to keep URLs stable. null=True only because a one-shot data migration backfills existing rows; new rows always get a slug via Season.save().",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public — listed on the discovery home and indexed."),
                    (
                        "unlisted",
                        "Unlisted — accessible by URL, hidden from discovery, noindex.",
                    ),
                    ("draft", "Draft — visible only to staff."),
                ],
                default="public",
                help_text="Discovery visibility. 'public' lists on /v2/ and indexes. 'unlisted' is accessible by URL only and emits noindex. 'draft' is staff-only (404 to anonymous).",
                max_length=16,
            ),
        ),
    ]
