# Generated by Django 4.2.22 on 2026-05-03 22:03

from django.db import migrations
from django.utils.text import slugify


def backfill_season_slugs(apps, schema_editor):
    Season = apps.get_model("tournament", "Season")
    seen: set[str] = set()
    for season in Season.objects.select_related("league").order_by("pk"):
        if season.slug:
            seen.add(season.slug)
            continue
        candidate = slugify(f"{season.league.tag}-{season.tag}-{season.id}")
        if candidate in seen:
            raise RuntimeError(
                f"slug collision during backfill: {candidate!r} for Season pk={season.pk}"
            )
        seen.add(candidate)
        season.slug = candidate
        season.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0054_season_slug_season_visibility"),
    ]

    operations = [
        migrations.RunPython(backfill_season_slugs, migrations.RunPython.noop),
    ]
