# Generated by Django 4.2.22 on 2026-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0055_backfill_season_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="organizer_name",
            field=models.CharField(
                blank=True,
                help_text="Override the organizer label shown on /v2/. Leave blank to default to the league's name. Use when a season runs under a different organizer than the league suggests (cross-league events, guest hosts, qualifiers).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="organizer_tag_override",
            field=models.SlugField(
                blank=True,
                help_text="Override the organizer chip-filter slug on /v2/. Leave blank to default to league.tag. Group seasons by organizer in the filter chip without renaming the league.",
                max_length=64,
            ),
        ),
    ]
