# Generated by Django 4.2.22 on 2026-05-04 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournament", "0056_season_organizer_name_season_organizer_tag_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("force_result", "Force result"),
                            ("mark_forfeit", "Mark forfeit"),
                            ("reschedule", "Reschedule"),
                        ],
                        max_length=32,
                    ),
                ),
                ("before_json", models.JSONField(blank=True, default=dict)),
                ("after_json", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cockpit_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pairing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cockpit_audit_entries",
                        to="tournament.playerpairing",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-date_created"],
                        name="tournament__actor_i_c3f770_idx",
                    ),
                    models.Index(
                        fields=["pairing", "-date_created"],
                        name="tournament__pairing_fd3f5f_idx",
                    ),
                ],
            },
        ),
    ]
