# Generated by Django 4.2.22 on 2026-05-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0058_backgroundjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLagSample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["-requested_at"], name="tournament__request_d5736e_idx"
                    )
                ],
            },
        ),
    ]
