# Generated by Django 4.2.22 on 2026-05-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0059_joblagsample"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLagBucket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=8,
                    ),
                ),
                ("bucket_start", models.DateTimeField()),
                ("sample_count", models.IntegerField()),
                ("queue_lag_mean", models.FloatField()),
                ("queue_lag_min", models.FloatField()),
                ("queue_lag_max", models.FloatField()),
                ("queue_lag_p95", models.FloatField()),
                ("queue_lag_stddev", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-bucket_start"],
                "indexes": [
                    models.Index(
                        fields=["granularity", "-bucket_start"],
                        name="tournament__granula_59fc02_idx",
                    )
                ],
                "unique_together": {("granularity", "bucket_start")},
            },
        ),
    ]
