FROM base AS builder

RUN python manage.py collectstatic --noinput

#####################################

FROM caddy:2-alpine AS caddy

COPY --from=builder /app/heltour/tournament/static /public/static
